### ISSUE TITLE
NameError: name 'image' is not defined

### ISSUE THREAD

**Issue by HAlanL** [Tony607/Keras_face_identification_realtime#5]
./data/face_images/barack
length: 216, w x h: 1280 x 720, fps: 25.0
length: 207, w x h: 1280 x 720, fps: 25.0
./data/face_images/chengwei
length: 181, w x h: 1280 x 720, fps: 29.966887417218544
length: 69, w x h: 1280 x 720, fps: 29.97827661115134
./data/face_images/michelle
length: 384, w x h: 1280 x 720, fps: 25.0
length: 96, w x h: 1280 x 720, fps: 25.0
Traceback (most recent call last):
  File "precompute_features.py", line 165, in <module>
    main()
  File "precompute_features.py", line 159, in main
    mean_features = cal_mean_feature(image_folder=save_folder)
  File "precompute_features.py", line 132, in cal_mean_feature
    images = np.concatenate([image2x(face_image) for face_image in face_images_chunk])
  File "precompute_features.py", line 132, in <listcomp>
    images = np.concatenate([image2x(face_image) for face_image in face_images_chunk])
  File "precompute_features.py", line 114, in image2x
    img = image.load_img(image_path, target_size=(224, 224))
NameError: name 'image' is not defined

**Comment by jaideep93** [comment]
You need to import image as follows:

from keras.preprocessing import image
